/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ATCProject;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author matankay
 * @author FuadMohamoud
 */
public class userInterface extends javax.swing.JPanel {

    /**
     * Creates new form 
     */
    public userInterface() {
        initComponents();
    }

    
      
    protected static final int PLAY_TIME = 7000;

    private int targetX;
    private int targetY;
    private int targetX2;
    private int targetY2;
    
    private long startTime;
    private int startX;
    private int startX2;
    private int startY; 
    private int startY2; 
    
    private int startX3;
    private int startY3; 
    
    private Color[] colors = new Color[]{Color.ORANGE, Color.CYAN};
    private int colorIndex;
     int speed = 250;
    int count=0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Plane1 = new javax.swing.JPanel();
        iconPlane1 = new javax.swing.JLabel();
        aircraftIDPlane1LBL1 = new javax.swing.JLabel();
        destinationPlane1LBL1 = new javax.swing.JLabel();
        controlPlane1LBL1 = new javax.swing.JLabel();
        altitudePlane1LBL1 = new javax.swing.JLabel();
        speedPlane1LBL1 = new javax.swing.JLabel();
        headingPlane1LBL1 = new javax.swing.JLabel();
        Plane2 = new javax.swing.JPanel();
        iconPlane2 = new javax.swing.JLabel();
        aircraftIDPlane1LBL2 = new javax.swing.JLabel();
        destinationPlane1LBL2 = new javax.swing.JLabel();
        controlPlane1LBL2 = new javax.swing.JLabel();
        altitudePlane1LBL2 = new javax.swing.JLabel();
        speedPlane1LBL2 = new javax.swing.JLabel();
        headingPlane1LBL2 = new javax.swing.JLabel();
        Plane3 = new javax.swing.JPanel();
        iconPlane3 = new javax.swing.JLabel();
        aircraftIDPlane1LBL3 = new javax.swing.JLabel();
        destinationPlane1LBL3 = new javax.swing.JLabel();
        controlPlane1LBL3 = new javax.swing.JLabel();
        altitudePlane1LBL3 = new javax.swing.JLabel();
        speedPlane1LBL3 = new javax.swing.JLabel();
        headingPlane1LBL3 = new javax.swing.JLabel();
        Plane4 = new javax.swing.JPanel();
        iconPlane = new javax.swing.JLabel();
        aircraftIDPlane1LBL = new javax.swing.JLabel();
        destinationPlane1LBL = new javax.swing.JLabel();
        controlPlane1LBL = new javax.swing.JLabel();
        altitudePlane1LBL = new javax.swing.JLabel();
        speedPlane1LBL = new javax.swing.JLabel();
        headingPlane1LBL = new javax.swing.JLabel();
        Plane5 = new javax.swing.JPanel();
        iconPlane4 = new javax.swing.JLabel();
        aircraftIDPlane1LBL4 = new javax.swing.JLabel();
        destinationPlane1LBL4 = new javax.swing.JLabel();
        controlPlane1LBL4 = new javax.swing.JLabel();
        altitudePlane1LBL4 = new javax.swing.JLabel();
        speedPlane1LBL4 = new javax.swing.JLabel();
        headingPlane1LBL4 = new javax.swing.JLabel();
        exitRoute = new javax.swing.JLabel();
        landingRoute = new javax.swing.JLabel();
        explosionfire = new javax.swing.JLabel();
        Plane6 = new javax.swing.JPanel();
        iconPlane5 = new javax.swing.JLabel();
        aircraftIDPlane1LBL5 = new javax.swing.JLabel();
        destinationPlane1LBL5 = new javax.swing.JLabel();
        controlPlane1LBL5 = new javax.swing.JLabel();
        altitudePlane1LBL5 = new javax.swing.JLabel();
        speedPlane1LBL5 = new javax.swing.JLabel();
        headingPlane1LBL5 = new javax.swing.JLabel();
        airportLB = new javax.swing.JLabel();
        controlPanel = new javax.swing.JPanel();
        utcDirection = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        controlMessage = new javax.swing.JTextArea();
        Collision = new javax.swing.JButton();
        AircraftDeparture = new javax.swing.JButton();
        AircraftLanding = new javax.swing.JButton();
        CollisionAvoidance = new javax.swing.JButton();
        airportRunWay = new javax.swing.JLabel();
        requestingArrival = new javax.swing.JLabel();
        ExitingPlane = new javax.swing.JLabel();
        collisionSpot = new javax.swing.JLabel();
        avoid1 = new javax.swing.JLabel();
        Avoid2 = new javax.swing.JLabel();
        crashSpot = new javax.swing.JLabel();
        realCollisionAvoid = new javax.swing.JLabel();

        setBackground(new java.awt.Color(62, 136, 83));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Plane1.setBackground(new java.awt.Color(204, 204, 204));
        Plane1.setVisible(false);

        iconPlane1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATCProject/DrawNorthPLane.png"))); // NOI18N
        iconPlane1.setOpaque(true);

        aircraftIDPlane1LBL1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aircraftIDPlane1LBL1.setText("AA263");

        destinationPlane1LBL1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        destinationPlane1LBL1.setText("IAD");

        controlPlane1LBL1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        controlPlane1LBL1.setText("A");

        altitudePlane1LBL1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        altitudePlane1LBL1.setText("001");

        speedPlane1LBL1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        speedPlane1LBL1.setText("36");

        headingPlane1LBL1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        headingPlane1LBL1.setText("120");

        javax.swing.GroupLayout Plane1Layout = new javax.swing.GroupLayout(Plane1);
        Plane1.setLayout(Plane1Layout);
        Plane1Layout.setHorizontalGroup(
            Plane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Plane1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(iconPlane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Plane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Plane1Layout.createSequentialGroup()
                        .addComponent(aircraftIDPlane1LBL1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destinationPlane1LBL1))
                    .addGroup(Plane1Layout.createSequentialGroup()
                        .addComponent(altitudePlane1LBL1)
                        .addGap(18, 18, 18)
                        .addComponent(speedPlane1LBL1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Plane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headingPlane1LBL1)
                    .addComponent(controlPlane1LBL1))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        Plane1Layout.setVerticalGroup(
            Plane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Plane1Layout.createSequentialGroup()
                .addGroup(Plane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Plane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Plane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aircraftIDPlane1LBL1)
                            .addComponent(destinationPlane1LBL1)
                            .addComponent(controlPlane1LBL1))
                        .addGap(16, 16, 16)
                        .addGroup(Plane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(altitudePlane1LBL1)
                            .addComponent(speedPlane1LBL1)
                            .addComponent(headingPlane1LBL1)))
                    .addGroup(Plane1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(iconPlane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(Plane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 390, 210, 70));

        Plane2.setBackground(new java.awt.Color(204, 204, 204));
        Plane2.setVisible(false);
        Plane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Plane2MouseClicked(evt);
            }
        });
        Plane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconPlane2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATCProject/DrawNorthPLane.png"))); // NOI18N
        iconPlane2.setOpaque(true);
        Plane2.add(iconPlane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 62, 54));

        aircraftIDPlane1LBL2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aircraftIDPlane1LBL2.setText("AA263");
        Plane2.add(aircraftIDPlane1LBL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 16, -1, -1));

        destinationPlane1LBL2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        destinationPlane1LBL2.setText("IAD");
        Plane2.add(destinationPlane1LBL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 16, -1, -1));

        controlPlane1LBL2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        controlPlane1LBL2.setText("A");
        Plane2.add(controlPlane1LBL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 16, -1, -1));

        altitudePlane1LBL2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        altitudePlane1LBL2.setText("001");
        Plane2.add(altitudePlane1LBL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 47, -1, -1));

        speedPlane1LBL2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        speedPlane1LBL2.setText("36");
        Plane2.add(speedPlane1LBL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 47, -1, -1));

        headingPlane1LBL2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        headingPlane1LBL2.setText("120");
        Plane2.add(headingPlane1LBL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 47, -1, -1));

        add(Plane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 210, 70));

        Plane3.setBackground(new java.awt.Color(204, 204, 204));
        Plane3.setVisible(false);

        iconPlane3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATCProject/DrawNorthPLane.png"))); // NOI18N
        iconPlane3.setOpaque(true);

        aircraftIDPlane1LBL3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aircraftIDPlane1LBL3.setText("AA263");

        destinationPlane1LBL3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        destinationPlane1LBL3.setText("IAD");

        controlPlane1LBL3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        controlPlane1LBL3.setText("A");

        altitudePlane1LBL3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        altitudePlane1LBL3.setText("001");

        speedPlane1LBL3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        speedPlane1LBL3.setText("36");

        headingPlane1LBL3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        headingPlane1LBL3.setText("120");

        javax.swing.GroupLayout Plane3Layout = new javax.swing.GroupLayout(Plane3);
        Plane3.setLayout(Plane3Layout);
        Plane3Layout.setHorizontalGroup(
            Plane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Plane3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(iconPlane3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Plane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Plane3Layout.createSequentialGroup()
                        .addComponent(aircraftIDPlane1LBL3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destinationPlane1LBL3))
                    .addGroup(Plane3Layout.createSequentialGroup()
                        .addComponent(altitudePlane1LBL3)
                        .addGap(18, 18, 18)
                        .addComponent(speedPlane1LBL3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Plane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headingPlane1LBL3)
                    .addComponent(controlPlane1LBL3))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        Plane3Layout.setVerticalGroup(
            Plane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Plane3Layout.createSequentialGroup()
                .addGroup(Plane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Plane3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Plane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aircraftIDPlane1LBL3)
                            .addComponent(destinationPlane1LBL3)
                            .addComponent(controlPlane1LBL3))
                        .addGap(16, 16, 16)
                        .addGroup(Plane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(altitudePlane1LBL3)
                            .addComponent(speedPlane1LBL3)
                            .addComponent(headingPlane1LBL3)))
                    .addGroup(Plane3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(iconPlane3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(Plane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, 210, 70));

        Plane4.setBackground(new java.awt.Color(204, 204, 204));
        Plane4.setVisible(false);

        iconPlane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATCProject/DrawNorthPLane.png"))); // NOI18N
        iconPlane.setOpaque(true);

        aircraftIDPlane1LBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aircraftIDPlane1LBL.setText("AA263");

        destinationPlane1LBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        destinationPlane1LBL.setText("IAD");

        controlPlane1LBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        controlPlane1LBL.setText("A");

        altitudePlane1LBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        altitudePlane1LBL.setText("001");

        speedPlane1LBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        speedPlane1LBL.setText("36");

        headingPlane1LBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        headingPlane1LBL.setText("120");

        javax.swing.GroupLayout Plane4Layout = new javax.swing.GroupLayout(Plane4);
        Plane4.setLayout(Plane4Layout);
        Plane4Layout.setHorizontalGroup(
            Plane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Plane4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(iconPlane, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Plane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Plane4Layout.createSequentialGroup()
                        .addComponent(aircraftIDPlane1LBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destinationPlane1LBL))
                    .addGroup(Plane4Layout.createSequentialGroup()
                        .addComponent(altitudePlane1LBL)
                        .addGap(18, 18, 18)
                        .addComponent(speedPlane1LBL)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Plane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headingPlane1LBL)
                    .addComponent(controlPlane1LBL))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        Plane4Layout.setVerticalGroup(
            Plane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Plane4Layout.createSequentialGroup()
                .addGroup(Plane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Plane4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Plane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aircraftIDPlane1LBL)
                            .addComponent(destinationPlane1LBL)
                            .addComponent(controlPlane1LBL))
                        .addGap(16, 16, 16)
                        .addGroup(Plane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(altitudePlane1LBL)
                            .addComponent(speedPlane1LBL)
                            .addComponent(headingPlane1LBL)))
                    .addGroup(Plane4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(iconPlane, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(Plane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 260, 210, 70));

        Plane5.setBackground(new java.awt.Color(204, 204, 204));
        Plane5.setVisible(false);

        iconPlane4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATCProject/DrawNorthPLane.png"))); // NOI18N
        iconPlane4.setOpaque(true);

        aircraftIDPlane1LBL4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aircraftIDPlane1LBL4.setText("AA263");

        destinationPlane1LBL4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        destinationPlane1LBL4.setText("IAD");

        controlPlane1LBL4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        controlPlane1LBL4.setText("A");

        altitudePlane1LBL4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        altitudePlane1LBL4.setText("001");

        speedPlane1LBL4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        speedPlane1LBL4.setText("36");

        headingPlane1LBL4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        headingPlane1LBL4.setText("120");

        javax.swing.GroupLayout Plane5Layout = new javax.swing.GroupLayout(Plane5);
        Plane5.setLayout(Plane5Layout);
        Plane5Layout.setHorizontalGroup(
            Plane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Plane5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(iconPlane4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Plane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Plane5Layout.createSequentialGroup()
                        .addComponent(aircraftIDPlane1LBL4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destinationPlane1LBL4))
                    .addGroup(Plane5Layout.createSequentialGroup()
                        .addComponent(altitudePlane1LBL4)
                        .addGap(18, 18, 18)
                        .addComponent(speedPlane1LBL4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Plane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headingPlane1LBL4)
                    .addComponent(controlPlane1LBL4))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        Plane5Layout.setVerticalGroup(
            Plane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Plane5Layout.createSequentialGroup()
                .addGroup(Plane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Plane5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Plane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aircraftIDPlane1LBL4)
                            .addComponent(destinationPlane1LBL4)
                            .addComponent(controlPlane1LBL4))
                        .addGap(16, 16, 16)
                        .addGroup(Plane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(altitudePlane1LBL4)
                            .addComponent(speedPlane1LBL4)
                            .addComponent(headingPlane1LBL4)))
                    .addGroup(Plane5Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(iconPlane4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(Plane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 230, -1, 70));

        exitRoute.setBackground(new java.awt.Color(51, 255, 51));
        exitRoute.setOpaque(true);
        add(exitRoute, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 70, 70));

        landingRoute.setBackground(new java.awt.Color(51, 255, 51));
        landingRoute.setOpaque(true);
        add(landingRoute, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 350, 70, 70));

        explosionfire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATCProject/fireexplosion (1).png"))); // NOI18N
        explosionfire.setText("jLabel1");
        add(explosionfire, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 230, 230));
        explosionfire.setVisible(false);

        Plane6.setBackground(new java.awt.Color(204, 204, 204));
        Plane6.setVisible(false);

        iconPlane5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATCProject/DrawNorthPLane.png"))); // NOI18N
        iconPlane5.setOpaque(true);

        aircraftIDPlane1LBL5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aircraftIDPlane1LBL5.setText("AA263");

        destinationPlane1LBL5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        destinationPlane1LBL5.setText("IAD");

        controlPlane1LBL5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        controlPlane1LBL5.setText("A");

        altitudePlane1LBL5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        altitudePlane1LBL5.setText("001");

        speedPlane1LBL5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        speedPlane1LBL5.setText("36");

        headingPlane1LBL5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        headingPlane1LBL5.setText("120");

        javax.swing.GroupLayout Plane6Layout = new javax.swing.GroupLayout(Plane6);
        Plane6.setLayout(Plane6Layout);
        Plane6Layout.setHorizontalGroup(
            Plane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Plane6Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(iconPlane5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Plane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Plane6Layout.createSequentialGroup()
                        .addComponent(aircraftIDPlane1LBL5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destinationPlane1LBL5))
                    .addGroup(Plane6Layout.createSequentialGroup()
                        .addComponent(altitudePlane1LBL5)
                        .addGap(18, 18, 18)
                        .addComponent(speedPlane1LBL5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Plane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headingPlane1LBL5)
                    .addComponent(controlPlane1LBL5))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        Plane6Layout.setVerticalGroup(
            Plane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Plane6Layout.createSequentialGroup()
                .addGroup(Plane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Plane6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Plane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aircraftIDPlane1LBL5)
                            .addComponent(destinationPlane1LBL5)
                            .addComponent(controlPlane1LBL5))
                        .addGap(16, 16, 16)
                        .addGroup(Plane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(altitudePlane1LBL5)
                            .addComponent(speedPlane1LBL5)
                            .addComponent(headingPlane1LBL5)))
                    .addGroup(Plane6Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(iconPlane5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(Plane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, 70));

        airportLB.setForeground(new java.awt.Color(62, 136, 83));
        airportLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATCProject/drawing1.jpg"))); // NOI18N
        add(airportLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, -10, -1, 760));

        utcDirection.setBackground(new java.awt.Color(255, 0, 51));
        utcDirection.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        utcDirection.setText("     UTC Directions");

        controlMessage.setColumns(20);
        controlMessage.setRows(5);
        jScrollPane2.setViewportView(controlMessage);

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                        .addComponent(utcDirection, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addComponent(utcDirection, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        add(controlPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 560, 540, 340));

        Collision.setText("Collision");
        Collision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CollisionMouseClicked(evt);
            }
        });
        add(Collision, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 840, 150, 60));

        AircraftDeparture.setText("Aircraft Departure");
        AircraftDeparture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AircraftDepartureMouseClicked(evt);
            }
        });
        add(AircraftDeparture, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 840, 180, 60));

        AircraftLanding.setText("Aircraft Landing");
        AircraftLanding.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AircraftLandingMouseClicked(evt);
            }
        });
        add(AircraftLanding, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 840, 150, 60));

        CollisionAvoidance.setText("Collision Avoidance");
        CollisionAvoidance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CollisionAvoidanceMouseClicked(evt);
            }
        });
        add(CollisionAvoidance, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 840, 180, 60));

        airportRunWay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                airportRunWayMouseClicked(evt);
            }
        });
        add(airportRunWay, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 260, 240));

        requestingArrival.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestingArrivalMouseClicked(evt);
            }
        });
        add(requestingArrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 0, 420, 120));
        add(ExitingPlane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 100, 90));
        add(collisionSpot, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 130, 70));
        add(avoid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1710, 420, 80, 80));
        add(Avoid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 840, 80, 40));
        add(crashSpot, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 100, 110, 130));
        add(realCollisionAvoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 580, 240, 150));
    }// </editor-fold>//GEN-END:initComponents

    private void AircraftLandingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AircraftLandingMouseClicked
       Plane4.setVisible(true);
        airportRunWay.setVisible(true);
       AircraftLanding.setVisible(true);
        startX = Plane4.getX();
        startY = Plane4.getY();
        //plane1.setVisible(true);
         controlMessage.append("Flight AA263 Landing Approved");
                
        targetX =  airportRunWay.getX();
        targetY =  airportRunWay.getY();
        
        
        Timer timer = new Timer(340, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int x = Plane4.getX();
                int y = Plane4.getY();

                
                long duration = System.currentTimeMillis() - startTime;
                float progress = (float)duration / (float)PLAY_TIME;

                if (progress > 1f) {
                    progress = 1f;
                    ((Timer)(e.getSource())).stop();

                }

                x = startX + (int)Math.round((targetX - startX) * progress);
                y = startY + (int)Math.round((targetY - startY) * progress);
                        
                Plane4.setLocation(x, y);
                if(x == targetX && y == targetY){
                    Plane4.setVisible(false);
                    controlMessage.append("\nFlight AA263 Landed Successifully\n");
                }
            }

            
        });
        
        
        startTime = System.currentTimeMillis();

        timer.start();
        
       speedPlane1LBL2.setText(String.valueOf(speed-10));
      
        
        
        
     
        
        
        
    }//GEN-LAST:event_AircraftLandingMouseClicked

    private void AircraftDepartureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AircraftDepartureMouseClicked
       
        
       AircraftDeparture.setVisible(true);
        startX = Plane2.getX();
        startY = Plane2.getY();
        //plane1.setVisible(true);
         controlMessage.append("\nFlight AA263 Departure Approved\n");
                
        targetX =  ExitingPlane.getX();
        targetY =  ExitingPlane.getY();
        
        
        Timer timer = new Timer(340, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int x = Plane2.getX();
                int y = Plane2.getY();

                
                long duration = System.currentTimeMillis() - startTime;
                float progress = (float)duration / (float)PLAY_TIME;

                if (progress > 1f) {
                    progress = 1f;
                    ((Timer)(e.getSource())).stop();

                }

                x = startX + (int)Math.round((targetX - startX) * progress);
                y = startY + (int)Math.round((targetY - startY) * progress);
                        
                Plane2.setLocation(x, y);
                if(x == targetX && y == targetY){
                    Plane2.setVisible(false);
                    
                }
            }

            
        });
        
        
        startTime = System.currentTimeMillis();

        timer.start();
        
       speedPlane1LBL2.setText(String.valueOf(speed-10));
    }//GEN-LAST:event_AircraftDepartureMouseClicked

    private void CollisionAvoidanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CollisionAvoidanceMouseClicked
       
         
       Plane3.setVisible(true);
        startX = Plane3.getX();
        startY = Plane3.getY();
        //plane1.setVisible(true);
         
                
        targetX =  avoid1.getX();
        targetY =  avoid1.getY();
        
        Plane1.setVisible(true);
        startX2 = Plane1.getX();
        startY2 = Plane1.getY();
        //plane1.setVisible(true);
        
                
        targetX2 =  Avoid2.getX();
        targetY2 =  Avoid2.getY();
        
        Timer timer = new Timer(340, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int x = Plane3.getX();
                int y = Plane3.getY();
                int x3 = Plane1.getX();
                int y3 = Plane1.getY();

                
                long duration = System.currentTimeMillis() - startTime;
                float progress = (float)duration / (float)PLAY_TIME;

                if (progress > 1f) {
                    progress = 1f;
                    ((Timer)(e.getSource())).stop();

                }

                x = startX + (int)Math.round((targetX - startX) * progress);
                y = startY + (int)Math.round((targetY - startY) * progress);
                        
                
                   
                x3 = startX2 + (int)Math.round((targetX2 - startX2) * progress);
                y3 = startY2 + (int)Math.round((targetY2 - startY2) * progress);
                
                
                if(x== realCollisionAvoid.getX() || y== realCollisionAvoid.getY()){
                   
                    
                     controlMessage.append("\nCollision Avoidance System Activated\n"); 
                     String heading = JOptionPane.showInputDialog("Input Heading");
        
                     String speed = JOptionPane.showInputDialog("Input speed");
        
                    String altitude = JOptionPane.showInputDialog("Input Altitude");
                   
                   
                    controlMessage.append("Flight AA263 Ascend 2 meters North East");
                    
                    
                    
                    
                }
                Plane3.setLocation(x, y);
                if(x == targetX && y == targetY){
                    Plane3.setVisible(false);   
                    
                }
                
                
                Plane1.setLocation(x3, y3);
                if(x3 == targetX2 && y3 == targetY2){
                    Plane1.setVisible(false);
                    
                }
            }

            
        });
        
        
        startTime = System.currentTimeMillis();

        timer.start();
        
       speedPlane1LBL2.setText(String.valueOf(speed-10));
              
        
        
    }//GEN-LAST:event_CollisionAvoidanceMouseClicked

    private void CollisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CollisionMouseClicked
         Plane6.setVisible(true);
        Plane5.setVisible(true);
        
        
        
        
        startX = Plane6.getX();
        startY = Plane6.getY();
        
        startX2 = Plane5.getX();
        startY2 = Plane5.getY();
        
       
        //plane1.setVisible(true);

        targetX = crashSpot.getX();
        targetY = crashSpot.getY();
        
        targetX2 = crashSpot.getX();
        targetY2 = crashSpot.getY();
        
        


        //altitudeLB3.setText("400");


        Timer timer = new Timer(340, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int x = Plane6.getX();
                int y = Plane6.getY();

                int x2 = Plane5.getX();
                int y2 = Plane5.getY();
              
                
                long duration = System.currentTimeMillis() - startTime;
                float progress = (float)duration / (float)PLAY_TIME;

                if (progress > 1f) {
                    progress = 1f;
                    ((Timer)(e.getSource())).stop();
                }

                x = startX + (int)Math.round((targetX - startX) * progress);
                y = startY + (int)Math.round((targetY - startY) * progress);
                
                x2 = startX2 + (int)Math.round((targetX - startX2) * progress);
                y2 = startY2 + (int)Math.round((targetY - startY2) * progress);
                
                
                Plane6.setLocation(x, y);
                Plane5.setLocation(x2, y2);
    
                
                
                if(x == targetX && y == targetY)
                {
          
                   
                   AudioInputStream audioInputStream = null;
                    try {
                         controlMessage.append("\nFlight AA263 has crashed\n");
                        
                        explosionfire.setVisible(true);
                         Plane5.setVisible(false);
                            Plane6.setVisible(false);
                        String soundName = "C:/Users/matankay/Downloads/Explosion+2.wav";
                        audioInputStream = AudioSystem.getAudioInputStream(new File(soundName).getAbsoluteFile());
                        Clip clip = AudioSystem.getClip();
                        clip.open(audioInputStream);
                        clip.start();
                    } catch (UnsupportedAudioFileException ex) {
                        Logger.getLogger(userInterface.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(userInterface.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (LineUnavailableException ex) {
                        Logger.getLogger(userInterface.class.getName()).log(Level.SEVERE, null, ex);
                    } finally {
                        try {
                            audioInputStream.close();
                        } catch (IOException ex) {
                            Logger.getLogger(userInterface.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
                   
                
                
                
                
                
            }
        });

        startTime = System.currentTimeMillis();

        timer.start();
    }//GEN-LAST:event_CollisionMouseClicked

    private void requestingArrivalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestingArrivalMouseClicked
        
        
          Plane4.setVisible(true);
        landingRoute.setVisible(true);
       requestingArrival.setVisible(false);
        startX = Plane4.getX();
        startY = Plane4.getY();
       
        
                
        targetX =  landingRoute.getX();
        targetY =  landingRoute.getY();
        
        
        Timer timer = new Timer(340, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int x = Plane4.getX();
                int y = Plane4.getY();

                
                long duration = System.currentTimeMillis() - startTime;
                float progress = (float)duration / (float)PLAY_TIME;

                if (progress > 1f) {
                    progress = 1f;
                    ((Timer)(e.getSource())).stop();

                }

                x = startX + (int)Math.round((targetX - startX) * progress);
                y = startY + (int)Math.round((targetY - startY) * progress);
                        
                Plane4.setLocation(x, y);
                if(x == targetX && y == targetY){
                
                    controlMessage.append("\nFlight AA263 Requesting Landing\n");
                }
            }

            
        });
        
        
        startTime = System.currentTimeMillis();

        timer.start();
        
       speedPlane1LBL2.setText(String.valueOf(speed-10));
        
        
        
    }//GEN-LAST:event_requestingArrivalMouseClicked

    private void airportRunWayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_airportRunWayMouseClicked
       Plane2.setVisible(true);
        airportRunWay.setVisible(true);
       AircraftLanding.setVisible(true);
        startX = Plane2.getX();
        startY = Plane2.getY();
        //plane1.setVisible(true);
         
                
        targetX =  airportRunWay.getX();
        targetY =  airportRunWay.getY();
        
        
        Timer timer = new Timer(340, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int x = Plane2.getX();
                int y = Plane2.getY();

                
                long duration = System.currentTimeMillis() - startTime;
                float progress = (float)duration / (float)PLAY_TIME;

                if (progress > 1f) {
                    progress = 1f;
                    ((Timer)(e.getSource())).stop();

                }

                x = startX + (int)Math.round((targetX - startX) * progress);
                y = startY + (int)Math.round((targetY - startY) * progress);
                        
                Plane2.setLocation(x, y);
                if(x == targetX && y == targetY){
                    
                    controlMessage.append("\nFlight AA263 requesting take off");
                }
            }

            
        });
        
        
        startTime = System.currentTimeMillis();

        timer.start();
        
       speedPlane1LBL2.setText(String.valueOf(speed-10));
    }//GEN-LAST:event_airportRunWayMouseClicked

    private void Plane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Plane2MouseClicked
       
        String heading = JOptionPane.showInputDialog("Input Heading");
        
        String speed = JOptionPane.showInputDialog("Input speed");
        
        String altitude = JOptionPane.showInputDialog("Input Altitude");
            
    }//GEN-LAST:event_Plane2MouseClicked


    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AircraftDeparture;
    private javax.swing.JButton AircraftLanding;
    private javax.swing.JLabel Avoid2;
    private javax.swing.JButton Collision;
    private javax.swing.JButton CollisionAvoidance;
    private javax.swing.JLabel ExitingPlane;
    private javax.swing.JPanel Plane1;
    private javax.swing.JPanel Plane2;
    private javax.swing.JPanel Plane3;
    private javax.swing.JPanel Plane4;
    private javax.swing.JPanel Plane5;
    private javax.swing.JPanel Plane6;
    private javax.swing.JLabel aircraftIDPlane1LBL;
    private javax.swing.JLabel aircraftIDPlane1LBL1;
    private javax.swing.JLabel aircraftIDPlane1LBL2;
    private javax.swing.JLabel aircraftIDPlane1LBL3;
    private javax.swing.JLabel aircraftIDPlane1LBL4;
    private javax.swing.JLabel aircraftIDPlane1LBL5;
    private javax.swing.JLabel airportLB;
    private javax.swing.JLabel airportRunWay;
    private javax.swing.JLabel altitudePlane1LBL;
    private javax.swing.JLabel altitudePlane1LBL1;
    private javax.swing.JLabel altitudePlane1LBL2;
    private javax.swing.JLabel altitudePlane1LBL3;
    private javax.swing.JLabel altitudePlane1LBL4;
    private javax.swing.JLabel altitudePlane1LBL5;
    private javax.swing.JLabel avoid1;
    private javax.swing.JLabel collisionSpot;
    private javax.swing.JTextArea controlMessage;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel controlPlane1LBL;
    private javax.swing.JLabel controlPlane1LBL1;
    private javax.swing.JLabel controlPlane1LBL2;
    private javax.swing.JLabel controlPlane1LBL3;
    private javax.swing.JLabel controlPlane1LBL4;
    private javax.swing.JLabel controlPlane1LBL5;
    private javax.swing.JLabel crashSpot;
    private javax.swing.JLabel destinationPlane1LBL;
    private javax.swing.JLabel destinationPlane1LBL1;
    private javax.swing.JLabel destinationPlane1LBL2;
    private javax.swing.JLabel destinationPlane1LBL3;
    private javax.swing.JLabel destinationPlane1LBL4;
    private javax.swing.JLabel destinationPlane1LBL5;
    private javax.swing.JLabel exitRoute;
    private javax.swing.JLabel explosionfire;
    private javax.swing.JLabel headingPlane1LBL;
    private javax.swing.JLabel headingPlane1LBL1;
    private javax.swing.JLabel headingPlane1LBL2;
    private javax.swing.JLabel headingPlane1LBL3;
    private javax.swing.JLabel headingPlane1LBL4;
    private javax.swing.JLabel headingPlane1LBL5;
    private javax.swing.JLabel iconPlane;
    private javax.swing.JLabel iconPlane1;
    private javax.swing.JLabel iconPlane2;
    private javax.swing.JLabel iconPlane3;
    private javax.swing.JLabel iconPlane4;
    private javax.swing.JLabel iconPlane5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel landingRoute;
    private javax.swing.JLabel realCollisionAvoid;
    private javax.swing.JLabel requestingArrival;
    private javax.swing.JLabel speedPlane1LBL;
    private javax.swing.JLabel speedPlane1LBL1;
    private javax.swing.JLabel speedPlane1LBL2;
    private javax.swing.JLabel speedPlane1LBL3;
    private javax.swing.JLabel speedPlane1LBL4;
    private javax.swing.JLabel speedPlane1LBL5;
    private javax.swing.JLabel utcDirection;
    // End of variables declaration//GEN-END:variables




    public static void main(String[] args){
        JFrame frame= new JFrame("Air Traffic Control System");
        frame.setContentPane(new userInterface());
        //Container c = frame.getContentPane();
        //c.setBackground(Color.lightGray);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
 }






}
